config/routes.rb
Rails.application.routes.draw do

  root "statics#landing"

  require 'sidekiq/web'
  authenticate :account, lambda { |a| a.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :accounts, controllers: {registrations: 'accounts/registrations', sessions: 'accounts/sessions'}
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :accounts, path: '' do 
    resources :rooms do
      resources :memberships, only: [:create, :delete]
      resources :messages, only: [:create, :delete] do 
        collection do 
          post :typing
        end
      end
    end
    resource :tokens, only: :create
  end  

  resources :webhook_endpoints

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: :create do 
        collection do 
          post :action
        end
      end
      resources :memberships, only: :create
      resources :rooms, only: :create
      resources :users, only: :create do 
        member do
          get :login
        end
      end
      match '*path' => 'base#path_not_found', via: :all
    end
  end

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :room
  enum role: [:regular, :api]
end

app/controllers/api/v1/memberships_controller.rb
class Api::V1::MembershipsController < Api::V1::BaseController
  
  after_action :add_request_headers

  def create
    @membership = Membership.new(membership_params)
    if @membership.save
        render :show, status: :ok
    else
        render_error(@membership.errors.full_messages)
    end
  end

  private 

  def membership_params
    params.permit(:user_id, :room_id)
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[ show edit update destroy ]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: "Membership was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.require(:membership).permit(:user_id, :room_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.user_id %></td>
        <td><%= membership.room_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @membership.room_id %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>