config/routes.rb
Rails.application.routes.draw do

  root "statics#landing"

  require 'sidekiq/web'
  authenticate :account, lambda { |a| a.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :accounts, controllers: {registrations: 'accounts/registrations', sessions: 'accounts/sessions'}
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :accounts, path: '' do 
    resources :rooms do
      resources :memberships, only: [:create, :delete]
      resources :messages, only: [:create, :delete] do 
        collection do 
          post :typing
        end
      end
    end
    resource :tokens, only: :create
  end  

  resources :webhook_endpoints

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: :create do 
        collection do 
          post :action
        end
      end
      resources :memberships, only: :create
      resources :rooms, only: :create
      resources :users, only: :create do 
        member do
          get :login
        end
      end
      match '*path' => 'base#path_not_found', via: :all
    end
  end

end

app/models/webhook_endpoint.rb
class WebhookEndpoint < ApplicationRecord
  serialize :events

  belongs_to :account

  after_create :set_secret

  scope :live, -> { where(status: 'live') }

  def record_log(level, code, event, msg, data)
    logs = self.logs || []
    logs = logs.unshift({
      time: Time.now.utc, 
      level: level.to_s, 
      code: code,
      event: event, 
      message: msg, 
      data: data
    }).slice!(0...100)
    self.update(logs: logs)
  end

  private

  def set_secret
    self.update(secret: "goss_#{SecureRandom.hex(12)}") unless secret.present?
  end

end

app/controllers/webhook_endpoints_controller.rb
class WebhookEndpointsController < ApplicationController
  before_action :set_webhook_endpoint, only: %i[ show edit update destroy ]

  # GET /webhook_endpoints or /webhook_endpoints.json
  def index
    @webhook_endpoints = WebhookEndpoint.all
  end

  # GET /webhook_endpoints/1 or /webhook_endpoints/1.json
  def show
  end

  # GET /webhook_endpoints/new
  def new
    @webhook_endpoint = WebhookEndpoint.new
  end

  # GET /webhook_endpoints/1/edit
  def edit
  end

  # POST /webhook_endpoints or /webhook_endpoints.json
  def create
    @webhook_endpoint = WebhookEndpoint.new(webhook_endpoint_params)

    respond_to do |format|
      if @webhook_endpoint.save
        format.html { redirect_to @webhook_endpoint, notice: "Webhook endpoint was successfully created." }
        format.json { render :show, status: :created, location: @webhook_endpoint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @webhook_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /webhook_endpoints/1 or /webhook_endpoints/1.json
  def update
    respond_to do |format|
      if @webhook_endpoint.update(webhook_endpoint_params)
        format.html { redirect_to @webhook_endpoint, notice: "Webhook endpoint was successfully updated." }
        format.json { render :show, status: :ok, location: @webhook_endpoint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @webhook_endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webhook_endpoints/1 or /webhook_endpoints/1.json
  def destroy
    @webhook_endpoint.destroy
    respond_to do |format|
      format.html { redirect_to webhook_endpoints_url, notice: "Webhook endpoint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_webhook_endpoint
      @webhook_endpoint = WebhookEndpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def webhook_endpoint_params
      params.require(:webhook_endpoint).permit(:account_id, :url, :events, :status, :logs, :secret)
    end
end

app/helpers/webhook_endpoints_helper.rb
module WebhookEndpointsHelper
end

app/views/webhook_endpoints/_form.html.erb
<%= form_with(model: webhook_endpoint) do |form| %>
  <% if webhook_endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(webhook_endpoint.errors.count, "error") %> prohibited this webhook_endpoint from being saved:</h2>

      <ul>
        <% webhook_endpoint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :events %>
    <%= form.text_field :events %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :logs %>
    <%= form.text_field :logs %>
  </div>

  <div class="field">
    <%= form.label :secret %>
    <%= form.text_field :secret %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/webhook_endpoints/edit.html.erb
<h1>Editing Webhook Endpoint</h1>

<%= render 'form', webhook_endpoint: @webhook_endpoint %>

<%= link_to 'Show', @webhook_endpoint %> |
<%= link_to 'Back', webhook_endpoints_path %>

app/views/webhook_endpoints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Webhook Endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Url</th>
      <th>Events</th>
      <th>Status</th>
      <th>Logs</th>
      <th>Secret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @webhook_endpoints.each do |webhook_endpoint| %>
      <tr>
        <td><%= webhook_endpoint.account_id %></td>
        <td><%= webhook_endpoint.url %></td>
        <td><%= webhook_endpoint.events %></td>
        <td><%= webhook_endpoint.status %></td>
        <td><%= webhook_endpoint.logs %></td>
        <td><%= webhook_endpoint.secret %></td>
        <td><%= link_to 'Show', webhook_endpoint %></td>
        <td><%= link_to 'Edit', edit_webhook_endpoint_path(webhook_endpoint) %></td>
        <td><%= link_to 'Destroy', webhook_endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Webhook Endpoint', new_webhook_endpoint_path %>

app/views/webhook_endpoints/new.html.erb
<h1>New Webhook Endpoint</h1>

<%= render 'form', webhook_endpoint: @webhook_endpoint %>

<%= link_to 'Back', webhook_endpoints_path %>

app/views/webhook_endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @webhook_endpoint.account_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @webhook_endpoint.url %>
</p>

<p>
  <strong>Events:</strong>
  <%= @webhook_endpoint.events %>
</p>

<p>
  <strong>Status:</strong>
  <%= @webhook_endpoint.status %>
</p>

<p>
  <strong>Logs:</strong>
  <%= @webhook_endpoint.logs %>
</p>

<p>
  <strong>Secret:</strong>
  <%= @webhook_endpoint.secret %>
</p>

<%= link_to 'Edit', edit_webhook_endpoint_path(@webhook_endpoint) %> |
<%= link_to 'Back', webhook_endpoints_path %>