config/routes.rb
Rails.application.routes.draw do

  root "statics#landing"

  require 'sidekiq/web'
  authenticate :account, lambda { |a| a.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :accounts, controllers: {registrations: 'accounts/registrations', sessions: 'accounts/sessions'}
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}

  resources :accounts, path: '' do 
    resources :rooms do
      resources :memberships, only: [:create, :delete]
      resources :messages, only: [:create, :delete] do 
        collection do 
          post :typing
        end
      end
    end
    resource :tokens, only: :create
  end  

  resources :webhook_endpoints

  # API
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :messages, only: :create do 
        collection do 
          post :action
        end
      end
      resources :memberships, only: :create
      resources :rooms, only: :create
      resources :users, only: :create do 
        member do
          get :login
        end
      end
      match '*path' => 'base#path_not_found', via: :all
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :account
    has_many :messages

    has_many :memberships
    has_many :users, through: :memberships

    def membership_for(user_id)
        return memberships.find_by(user_id: user_id)
    end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::BaseController
  
  after_action :add_request_headers

  def create
    @room = Room.new(room_params)
    if @room.save
        render :show, status: :ok
    else
        render_error(@room.errors.full_messages)
    end
  end

  private 

  def room_params
    params.permit(:account_id, :name)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_auth_link, only: %i[ show ]
  before_action :authenticate_user!
  before_action :set_account, only: %i[ index ]
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :authenticate_membership, only: [:show]


  # GET /rooms or /rooms.json
  def index
    @rooms = @account.rooms
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    
    @membership = @room.membership_for(current_user.id)

    # @pagy, @messages = pagy(@room.messages.order(created_at: :desc), items: 20)

    
    if params[:jsload]
      
      @pagy, @messages = pagy(@room.messages.order(created_at: :desc), page: params[:page])

      html = @messages.map { |m| [render_to_string(partial: "messages/message", locals: { message: m, primary: (m.user == current_user), ref: m.id, status: "delivered", with_class: "" } )] }

      render json: { html: html, pagination: (view_context.pagy_nav(@pagy) if @pagy.present? ) }
    end

  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def authenticate_auth_link
      if params[:auth].present?
        begin
          jwt_payload = JWT.decode(params[:auth], Rails.application.secrets.secret_key_base).first
          user = User.find_by(id: jwt_payload['id'])
          sign_in(:user, user) if user.present?
        rescue JWT::ExpiredSignature, JWT::VerificationError, JWT::DecodeError
          return false
        end
      end
    end
    
    def authenticate_membership
      redirect_to root_url, alert: "Access Denied" unless current_user.is_member?(@room)
    end

    def set_account
      @account = Account.friendly.find(params[:account_id])
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms by <%= @account.email %></h1>  

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Show', account_room_path(room.account, room) %></td>
        <td><%#= link_to 'Edit', edit_room_path(room) %></td>
        <td><%#= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Room', new_room_path %>




<hr>


<p class="navbar-text float-right">
<% if user_signed_in? %>
  User Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  User
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>


<hr>

<p class="navbar-text float-right">
<% if account_signed_in? %>
  Account Logged in as <strong><%= current_account.email %></strong>.
  <%= link_to 'Edit profile', edit_account_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_account_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  Account
  <%= link_to "Sign up", new_account_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_account_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<!-- TODO: Improve config settings -->
<style>
  <% @room.config["style"].each do |k, v| %>
    .custom-<%= k %> {
      background-color: <%= v %> !important;
    }
  <% end %>
</style>


<div data-account-slug="<%= @room.account.slug %>" data-room-id="<%= @room.id %>" data-user-id="<%= current_user.id %>" data-role="<%= @membership.role %>" id="room" class="room-wrapper pb-24" style="overscroll-behavior: none;">

  <!-- HEADER -->
  <div class="fixed w-full bg-blue-400 h-16 pt-2 text-white flex justify-between shadow-md z-10 custom-header" style="top:0px; overscroll-behavior: none;">
    
    <a href="#">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-12 h-12 my-1 text-blue-100 ml-2"><path class="text-blue-100 fill-current" d="M9.41 11H17a1 1 0 0 1 0 2H9.41l2.3 2.3a1 1 0 1 1-1.42 1.4l-4-4a1 1 0 0 1 0-1.4l4-4a1 1 0 0 1 1.42 1.4L9.4 11z"/></svg>
    </a>
    <div class="my-3 text-blue-100 font-bold text-lg tracking-wide">
      <%= @room.name %>
    </div>

    <%= inline_svg_tag('icons/menu.svg', class: "w-8 h-8 mt-2 mr-2 text-white", height: "24px", width: "24px") %>
      
  </div>

  <!-- MESSAGES --> 
  <div class="js-infinite-scroll-pagination w-full mt-4">
    <%= inline_svg_tag("icons/loading.svg", options={width: "40", height: "40", style: "color: #cecece", class: "mx-auto has-text-primary"}) %>
  </div>
  
  <div class="messages mt-20 mb-16 js-infinite-scroll-container" data-has-resources="false" id="messages">
  </div>

  <%= render "messages/typing" %>

  <!-- FORM -->
  <%= render "messages/form", message: Message.new, room: @room %>

</div>